# Generated by Django 4.2.1 on 2023-05-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_reating_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("complain_text", models.TextField(max_length=300)),
                ("order_id", models.CharField(max_length=6)),
            ],
        ),
    ]
